name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Download CEF
      run: wget -O cef.tar.bz2 https://cef-builds.spotifycdn.com/cef_binary_88.1.6%2Bg4fe33a1%2Bchromium-88.0.4324.96_linux64_minimal.tar.bz2
    - name: Extract CEF headers
      run: tar -xf cef.tar.bz2 --wildcards '*/include' --strip-components=1
    - name: Run make
      run: make
    - name: Create build artifact
      uses: actions/upload-artifact@v1
      with:
        name: spotify-adblock.so
        path: spotify-adblock.so
